apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres.yaml
  - app.yaml

commonLabels:
  app.kubernetes.io/part-of: spring-boot-docker-demo
  app.kubernetes.io/managed-by: kustomize 